apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysqlRootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlUser | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/message.sql
              subPath: message.sql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
        - name: initdb
          configMap:
            name: {{ .Release.Name }}-mysql-initdb
