apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flaskapp
  labels:
    app: {{ .Release.Name }}-flaskapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flaskapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flaskapp
    spec:
      containers:
        - name: flaskapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}

